# Central configuration for the Java history service.
# {8106} is the default port for this service, but it can be overridden by setting the HISTORY_PORT environment variable.

# This is just a armless comment to test the analyzer...

port=8106
serviceName=history-service
